### PR TITLE
#124 Unique constraint violations are not propagated

### PR DESCRIPTION
**Pull request by tomhreb**
Hi!

I have not found better way for detecting which field constraint was violated than "parsing" the exception message.

I've added couple test methods into the test host, as it does not seem there is a unit test approach for the persistence provider.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
I think the message you test for is too specific. It is very easy to break that. Perhaps you can just check for "_id"?

**Comment by tomhreb** [comment]
ok, changed.

**Comment by SebastianStehle** [comment]
I want to step back, so it is up to @wassim-k to decide

**Comment by wassim-k** [comment]
good work @tomhreb, can you please just bump the version number in the csproj file and we'll get it merged.

**Comment by tomhreb** [comment]
@wassim-k done

**Pull request merged**
