### PR TITLE
Modify the DataTime type' storage format from String to Date Type in MongoDB

### PR DESCRIPTION
**Pull request by sdghchj**
it's more convenient for MongoDB driver to query by date.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
It needs to be configurable, otherwise it would break the compatibility.

**Comment by sdghchj** [comment]
yeah, but DateTime value's old format in MongoDB is String. When deserializing it to DataTime member in a grain state, the following line is run:
`case BsonType.String:
                    return new JValue(source.AsString);`
,
not the following line:
`case BsonType.DateTime:
                    return new JValue(source.ToLocalTime());`

When WriteStateAsync method is called, the DateTime member will be update to MongoDB date type by running the following line:
`case JTokenType.Date:`

That is, the two old code lines with 'case XXXX.DateTime' have never been run actually.
So I don't think my modification breaks the compatibility of course expect that the old MongoDB data is also used by some other integrated systems.

**Comment by sdghchj** [comment]
After all, I think it's very unfriendly to store DateTime type data as String type data in any date-type-surpported database. Could you please solve this issue?

**Comment by sdghchj** [comment]
Re-check please. I have made  it configurable .

**Pull request closed without merging**
