### PR TITLE
Simplified

### PR DESCRIPTION
**Pull request by SebastianStehle**
This PR is not done yet, but I would like to get your feedback.

I simplified some of the repository (membership is still missing). During this process I also got rid of some unnecessary queries. e.g. in `MongoReminderTableRepository.UpsertReminderRowAsync`. My goal was to have one repository per collection, because it was hard to understand which indexes are created.

I also updated the statistics stuff to keep old data for a defined period of time. But it is not used yet.

What do you think? 

Btw: It is not tested yet.

### CODE REVIEW

**Comment by laredoza** [comment]
This was my first MongoDb project I was involved with, consequently I'd change quite a few things.  I chose the repository pattern as I wasn't quite sure which driver I was going to end up with. I used the official driver, but I wanted to be able to swop it out with minimum work. After a year or so working with Mongo, I doubt the official drivers will ever need to be swapped out.  At the moment I think the repository pattern is over kill. I'd rather just have the base generic document repository (to insert, delete, query,etc) and put most of the logic in the providers. The storage provider is an example of how I would do it now.  I would just replace the select, inserts & deletes with the generic repository. Having a provider and repository patterns together seems overkill. Is it worth changing? Not sure to be honest.

If we're removing the repository interfaces, it's not really following the repository pattern anymore. At that point we might as well move most of the database functions into the providers, or just name the repository class  something else. Not sure how you feel about it?

**Comment by SebastianStehle** [comment]
The Repository pattern is misused so often (including from me) that I don't care anymore. I mean the idea was to store business objects and not dto's and I see so many wrong implementations.

I agree with you that the official driver will never be swapped out. In MongoDB the driver are very important, because you have no "frontend "servers that handle stuff like which node is reachable. Therefore I think the coupling is no problem. If we just rename Table to Document and Repository to Collection it would make sense. I think it makes sense to keep the provider and the repositories/collections separate to keep the files small.

**Comment by laredoza** [comment]
Sounds good.

**Comment by SebastianStehle** [comment]
Hi, I continued with the StorageProvider and created some first tests. Now I would like to implement the Storage Provider Semantics (https://dotnet.github.io/orleans/Documentation/Getting-Started-With-Orleans/Grain-Persistence.html). Are you interested to merge this fork in a branch and add me as contributor? Would be nice if we can make a v1.0 version out of it with support for Orleans2.0 and Orleans 1.X.

I am a little bit lost with the other tests.

**Comment by laredoza** [comment]
I've added you as a contributor. I agree that it would be great to get to v1.

I've merged your previous pull request but this pr is more significant and needs to be done on my client side. Picked up quite a few issues( looks like it's mostly reference related, It seems that the new preview libraries are dotnet standard 2.0, anyways, that's my suspicion). I will look at it tonight, otherwise if you'd like to merge it yourself, you're welcome to as well.

image

**Comment by SebastianStehle** [comment]
This is a super bad PR. I am going to push it to a vNext branch or so and then continue on this branch.

**Pull request closed without merging**
